name: Test Docker Build Issue
on: [push]

jobs:
  test-fleet:
    runs-on:
      - codebuild-test_job_summary_workflow_error-${{ github.run_id }}-${{ github.run_attempt }}
      - fleet:myTestFleet
      - image:arm-3.0
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Runtime Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
          load: true
          tags: test-image:latest
          platforms: linux/arm64
          provenance: false
