name: Test Docker Build Issue
on: [push]

jobs:
  Test-Fleet-Job:
    runs-on:
      - codebuild-workflow-test-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:myTestFleetx86
        image:ubuntu-5.0
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build runtime image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
          load: true
          provenance: false
