name: Test Docker Build Issue
on: [push]

jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-test-project-worflow-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:myTestFleet
        image:arm-3.0
    steps:
      - run: echo "Hello World"
